### ISSUE TITLE
Unable to retrieve mail content

### ISSUE THREAD

**Issue by blackheaven** [jtdaugherty/HaskellNet#27]
Hello,

I'm trying to run example/imap.hs with my gmail account and all I get is a bunch of empty strings for the content of the mails.
Is it normal or not?

Thanks in advance.

**Comment by blackheaven** [comment]
I'm not sure that it will be useful since I use a SSL connexion.

**Comment by jtdaugherty** [comment]
Okay. Given the information presented so far, we cannot determine the cause without more investigation. In order to do that, I need you to consider potential ways to get more intermediate information - such as by hacking the library to print out bytestrings fresh off the wire before intermediate handling, etc. I imagine there is a bug in the library, but I need you to try to narrow it down. Thanks!

**Comment by lemol** [comment]
Hacking IMAP.hs I found that there is a bug in use of the `lookup` function. I wrote the `lookup'` function to solve the problem. So, hope  81b8feb6cd0df57841ff71caf07e35272d841a3b can solve the problem!

**Comment by blackheaven** [comment]
I hope so, I'm also trying to debug it but I'm not used to.

**Comment by blackheaven** [comment]
Your PR #26 fix my issue, thanks
