### ISSUE TITLE
Add support for in-memory Mime attachments

### ISSUE THREAD

**Issue by MHova** [jtdaugherty/HaskellNet#32]
Allow clients to specify Mime attachments in the form of `(Text, ByteString)` instead of `(Text, FilePath)` where the `ByteString` is the raw attachment data.

**Comment by lemol** [comment]
I think this issue is about the [mime-mail](https://hackage.haskell.org/package/mime-mail) package. Can you post it [there](https://github.com/snoyberg/mime-mail/issues)? If so, I can write a patch for this feature in the mime-mail package.

**Comment by jtdaugherty** [comment]
In particular, it looks like a pure variant of `simpleMail` would be nice to have, with a version in `IO` that takes `FilePath` values for convenience.

**Comment by lemol** [comment]
Before releasing a new version, any suggestion for the function name?
I also added a function (`sendMimeMail2`) to send a mail with provided `Mail` data.

**Comment by jtdaugherty** [comment]
Naming that is a challenge, since I think `sendMail` is the best name, but that name is already taken.  Looking at the API, I think the library has too many specific ways to send mail.  I think a better API would be to permit the user to use many ways to construct a message, but only one or two ways to *send* it.  But I know that's a bigger task than just resolving this issue.

**Comment by lemol** [comment]
Exactly. I also think in that different API. I will propose it soon in another issue.
Then for now I think we can "bump version" with these names.
